### ISSUE TITLE
Mudar nome do projeto "GLOSSBOT"

### ISSUE THREAD

**Issue by brunocardoso749** [brunocardoso749/OPE#2]
## Mudar o nome do CHATBOT "GLOSSBOT"

**SUGESTÕES**

- Jerry
- Pinky
- Bender
- Doug
- Bart
- Fry
- Hubert

**Comment by maxlima-tech** [comment]
Seu Barriguinha (com fotinho do seu barriga do Chaves desenho) como alusão a "cobrança".

**Comment by brunocardoso749** [comment]
Show @maxwlima10. O nome do nosso projeto irá ficar como "Senhor Barriguinha".
